# Generated by Django 5.2.8 on 2025-11-15 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('kvartira', 'Квартира'), ('dom', 'Дом'), ('ofis', 'Офис'), ('dets', 'Детская'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='application',
            name='design_image',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято в работу'), ('done', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
